config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:confirmations, :mailer, :passwords]
  resources :books

  root to: "books#index"

  get 'users/loans' => "loans#show", as: :user_loans
  get 'users/all_loans' => "loans#index", as: :all_user_loans
  post 'users/create_loan' => "loans#create", as: :create_user_loan
  delete 'users/destroy_loan' => "loans#destroy", as: :delete_loan

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :loans
	has_many :users, through: :loans
	has_attached_file :cover
	validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

	validates_presence_of :title, :author, :description, :quantity

	def num_available 
		quantity - loans.size
	end

	def is_available?
		quantity - loans.size > 0
	end

	def contains_user?(user)
		loans.each { |l| return true if l.user_id == user.id }
		false
	end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  def checkout_date 
  	created_at.to_date.to_s(:db)
  end

  def due_date
  	(created_at + 14.days).to_date.to_s(:db)   
  end

 def self.money_owed(current_user)
  	total = 0
  	Loan.where(user_id: current_user).each { |loan| 
  		if loan.created_at.to_date + 30.days < Date.current
  			total += 5
  		elsif loan.created_at.to_date + 20.days < Date.current
  			total += 3
  		elsif loan.created_at.to_date == Date.current
  			total += 1
  		end
  	}
  	total
	end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :loans
  has_many :books, through: :loans

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 
	def require_admin
		unless current_user && current_user.admin?
	  		redirect_to root_path
		end
	end

 private 
	def require_user
		unless current_user && !current_user.admin?
	  		redirect_to root_path
		end
	end    

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_filter :require_admin, only: [:new, :create, :edit, :update, :destroy]

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to action: 'index'
		else 
			render 'new'
		end
	end

	def index
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.update(book_params)
		redirect_to action: 'index'
	end

	def destroy
		@book = Book.find(params[:id])
		Loan.where(book_id: @book).destroy_all
		@book.destroy
		redirect_to action: 'index'
	end 

	private
		def book_params
			params.require(:book).permit(:title, :author, :year, :publisher, :genre, :description, :quantity, :cover)
		end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
	before_filter :authenticate_user!
	before_filter :require_user, only: [:create]
	before_filter :require_admin, only: [:index, :destroy]

	def create
		Book.find(params[:id]).loans.create(user: current_user)
		redirect_to :action => 'show'
	end
	
	def show
		@loans = Loan.where(user_id: current_user)
	end

	def index
		@loans = Loan.all
	end

	def destroy
		if params.has_key?(:id)
  			Loan.destroy(params[:loan_ids])
		end
		redirect_to :action => 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
	<ul>
		<% @book.errors.full_messages.each do |error| %>
		<li> <%= error %> </li>
		<% end %>
	</ul>
	 <div class= "form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
    	<%= f.label :cover %> <br/>
		<%= f.file_field :cover %>
    </div>
    <div class="form-group">
    	<%= f.label :author %> <br/>
		<%= f.text_field :author, class: "form-control"%>
    </div>
    <div class="form-group">
    	<%= f.label :publisher %> <br/>
		<%= f.text_field :publisher, class: "form-control" %>
    </div>	
	<div class="form-group">
		<%= f.label :year %> <br/>
		<%= f.text_field :year, class: "form-control"  %>
	</div>
	<div class="form-group">
		<%= f.label :genre %> <br/>
		<%= f.text_field :genre, class: "form-control"  %>
	</div>
	<div class="form-group">
		<%= f.label :description %> <br/>
		<%= f.text_field :description, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :quantity %> <br/>
		<%= f.number_field :quantity, min: 1,  class: "form-control" %>
	</div>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Edit Book</h1>
		<%= render partial: 'form' %>
	</div>
</div>

app/views/books/index.html.erb
<h1 class="text-center">Catalogue</h1>
<div class="row">
	<% @books.each do |book| %>
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">
	      <%= image_tag book.cover.url %>
	      <div class="caption">
	        <h3><%= book.title %></h3>
	        	<% if user_signed_in? && current_user.admin %>
	        		<%= link_to "Edit", edit_book_path(book), class: "btn btn-default" %>
					<%= link_to "Delete", book_path(book), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-default" %>
        		<% elsif user_signed_in? && !current_user.admin? && book.contains_user?(current_user) %>
					<button type="button" class="btn btn-warning pull-left">Already Taken Out</button>
				<% elsif book.is_available?%>
					<%= button_to 'Take Out', { :controller => "loans", :action => "create", :book_id => book.id, :method=>:post }, class: "btn btn-primary pull-left" %>
	        	<% else %>
	        		<button type="button" class="btn btn-danger pull-left">No Stock</button>
	        	<% end %>
	        	<%= link_to "View Info", book_path(book), class: "btn btn-default" %>
      		</div>
   		 </div>
  	</div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @book, html: { multipart: true } do |f| %>
			<h1>New Book</h1>
			<ul>
				<% @book.errors.full_messages.each do |error| %>
				<li> <%= error %> </li>
				<% end %>
			</ul>
			 <div class= "form-group">
		          <%= f.label :title %>
		          <%= f.text_field :title, class: "form-control" %>
	        </div>
	        <div class="form-group">
	        	<%= f.label :cover %> <br/>
				<%= f.file_field :cover %>
	        </div>
	        <div class="form-group">
	        	<%= f.label :author %> <br/>
				<%= f.text_field :author, class: "form-control"%>
	        </div>
	        <div class="form-group">
	        	<%= f.label :publisher %> <br/>
				<%= f.text_field :publisher, class: "form-control" %>
	        </div>	
			<div class="form-group">
				<%= f.label :year %> <br/>
				<%= f.text_field :year, class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.label :genre %> <br/>
				<%= f.text_field :genre, class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.label :description %> <br/>
				<%= f.text_field :description, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :quantity %> <br/>
				<%= f.number_field :quantity, min: 1,  class: "form-control" %>
			</div>
			<%= f.submit class: "btn btn-primary" %>
		<% end %>
	</div>
</div>
	

app/views/books/show.html.erb
<h1>Book</h1>
<p>Title: <%= @book.title %></p>
<p>Author: <%= @book.author %></p>
<p>Year: <%= @book.year %></p>
<p>Publisher: <%= @book.publisher %></p>
<p>Genre: <%= @book.genre %></p>
<%= image_tag @book.cover.url %>
<h2>Description:</h2>
<p><%= @book.description %></p>
<p>Quantity: <%= @book.quantity %></p>
<% if @book.is_available? %>
	<p>Available: <%= @book.num_available %> </p>
<% else %>
	<p>Unavailable</p>
<% end %>
<% if user_signed_in? and @book.contains_user?(current_user) %>
	<p>Already Taken Out</p>
<% else %>
	<% if (user_signed_in?  && !current_user.admin?) || !user_signed_in? %>
		<%= button_to 'Take Out', { :controller => "loans", :action => "create", :book_id => @book.id, :method=>:post }, class: "btn btn-primary" %>
	<% else %>
		<%= link_to "Edit", edit_book_path(@book), class: "btn btn-default" %>
		<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-default" %>
	<% end %>
<% end %>		

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
  			</button>
			<%= link_to "LibraryRails", books_path, class: "navbar-brand" %>
		</div>
		<div class="navbar-collapse collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<% if current_user.admin? %>
						<li><%= link_to "New Book", new_book_path %></li>
						<li><%= link_to "All User Loans", all_user_loans_path %></li>
					<% end %>
					<% if !current_user.admin? %>
						<li><%= link_to "Loans", user_loans_path %></li>
					<% end %>
			    	<li><%= link_to "Account info", edit_user_registration_path %></li> 
			        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
	    			<li><%= link_to "Sign in", new_user_session_path %></li>
	    			<li><%= link_to "Sign up", new_user_registration_path %></li>
				<% end %> 
			</ul>
		</div>
	</div>
</nav> 

l

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/loans/index.html.erb
<h1>All Loans Taken Out</h1>
<%= form_tag delete_loan_path, method: :delete do %>
	<table class="table table-bordered">
		<tr>
			<th>User ID</th>
			<th>Email</th>
			<th>Title</th>
			<th>Check Out Date</th>
			<th>Due Date</th>
			<th>Returned?</th>
		</tr>
		<% @loans.each do |loan| %>
			<tr>
				<td> <%= loan.user_id %></td>
				<td> <%= User.find(loan.user_id).email %> </td>
				<td> <%= link_to Book.find(loan.book_id).title, book_path(loan.book_id) %> </td>
				<td> <%= loan.checkout_date %> </td>
				<td> <%= loan.due_date %> </td>
	  			<td><%= check_box_tag "loan_ids[]", loan.id %></td>
			</tr>
		<% end %>
	</table>
	<%= submit_tag "Delete Selected", class: "btn btn-primary" %>
<% end %>

app/views/loans/show.html.erb
<h1>All User Loans</h1>

<table class="table table-bordered">
	<tr>
		<th>Title</th>
		<th>Check Out Date</th>
		<th>Due Date</th>
	</tr>
	<% @loans.each do |loan| %>
		<tr>
			<td> <%= link_to Book.find(loan.book_id).title, book_path(loan.book_id) %></td>
			<td> <%= loan.checkout_date %> </td>
			<td> <%= loan.due_date %> </td>
		</tr>
	<% end %>
</table>

<p>Money owned? </p>
<p>
	<%= number_to_currency(Loan.money_owed current_user) %>
</p>